import { Receipt, CreditCard } from 'lucide-react'
import { useSimulationStore } from '../../lib/simulationStore'
import type { BackendEvent, Invoice } from '../../types'

function getEventSequence(event: BackendEvent) {
  return Number(event.sequence_number ?? event.sequence ?? 0)
}

function getInvoice(event: BackendEvent): Invoice | null {
  const payload = (event.data || event.payload || {}) as Record<string, unknown>
  if (!payload.invoice_id && !payload.id) return null
  return payload as unknown as Invoice
}

function formatRupees(amount: number) {
  return `\u20B9${amount.toLocaleString()}`
}

export function TransactionDashboard() {
  const { systemState, confirmPayment, generateRandomEvent } = useSimulationStore()
  const invoiceEvents = systemState.events
    .filter((event) => event.type === 'invoice_generated')
    .sort((a, b) => getEventSequence(b) - getEventSequence(a))

  const orders = invoiceEvents
    .map((event) => getInvoice(event))
    .filter((invoice): invoice is Invoice => Boolean(invoice))

  const totalOrders = orders.length
  const totalPending = orders.filter((invoice) => invoice.status !== 'paid').reduce((sum, invoice) => sum + Number(invoice.total || 0), 0)
  const totalPaid = orders.filter((invoice) => invoice.status === 'paid').reduce((sum, invoice) => sum + Number(invoice.total || 0), 0)
  const latestPendingInvoice = orders.find((invoice) => invoice.status !== 'paid')

  return (
    <div className="flex h-full flex-col rounded-md border border-[#d9dce3] bg-white shadow-sm">
      <div className="flex items-center justify-between border-b border-[#e7e9ee] px-4 py-3">
        <div>
          <h2 className="text-sm font-semibold text-[#1f2937]">Business Dashboard</h2>
          <p className="text-xs text-[#6b7280]">Control and backend order history</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => void generateRandomEvent()}
            className="rounded-md border border-[#d9dce3] bg-white px-3 py-2 text-xs font-semibold text-[#1f2937] transition-colors hover:bg-[#f8fafc]"
          >
            Generate Event
          </button>
          {latestPendingInvoice && (
            <button
              onClick={() => void confirmPayment()}
              className="rounded-md bg-[#0f766e] px-3 py-2 text-xs font-semibold text-white transition-colors hover:bg-[#115e59]"
            >
              Pay Now
            </button>
          )}
        </div>
      </div>

      <div className="grid gap-3 border-b border-[#e7e9ee] bg-[#f8fafc] p-4 md:grid-cols-2">
        <div className="rounded-md border border-[#d9dce3] bg-white p-3">
          <div className="mb-2 flex items-center gap-2 text-[#1f2937]">
            <Receipt size={16} />
            <span className="text-xs font-semibold uppercase tracking-[0.2em]">Orders</span>
          </div>
          <p className="text-2xl font-semibold text-[#111827]">{totalOrders}</p>
          <p className="text-xs text-[#6b7280]">Invoices generated by backend</p>
        </div>

        <div className="rounded-md border border-[#d9dce3] bg-white p-3">
          <div className="mb-2 flex items-center gap-2 text-[#1f2937]">
            <CreditCard size={16} />
            <span className="text-xs font-semibold uppercase tracking-[0.2em]">Payment Ledger</span>
          </div>
          <div className="flex items-center justify-between text-sm text-[#111827]">
            <span>Paid</span>
            <span className="font-semibold">{formatRupees(totalPaid)}</span>
          </div>
          <div className="mt-2 flex items-center justify-between text-sm text-[#111827]">
            <span>Pending</span>
            <span className="font-semibold">{formatRupees(totalPending)}</span>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-auto p-4">
        <div className="overflow-hidden rounded-md border border-[#d9dce3]">
          <table className="min-w-full divide-y divide-[#e7e9ee] text-sm">
            <thead className="bg-[#f8fafc]">
              <tr className="text-left text-xs uppercase tracking-[0.2em] text-[#6b7280]">
                <th className="px-4 py-3">ID</th>
                <th className="px-4 py-3">Customer</th>
                <th className="px-4 py-3">Amount</th>
                <th className="px-4 py-3">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#e7e9ee] bg-white">
              {orders.length === 0 ? (
                <tr>
                  <td colSpan={4} className="px-4 py-8 text-center text-sm text-[#6b7280]">
                    No invoice available
                  </td>
                </tr>
              ) : (
                orders.map((invoice) => (
                  <tr key={invoice.invoice_id} className="text-[#111827]">
                    <td className="px-4 py-3 font-mono text-xs">{invoice.invoice_id}</td>
                    <td className="px-4 py-3">{invoice.customer || 'Walk-in customer'}</td>
                    <td className="px-4 py-3">{formatRupees(Number(invoice.total || 0))}</td>
                    <td className="px-4 py-3">
                      <span
                        className={
                          invoice.status === 'paid'
                            ? 'rounded bg-[#dcfce7] px-2 py-1 text-xs font-semibold uppercase text-[#166534]'
                            : 'rounded bg-[#fef3c7] px-2 py-1 text-xs font-semibold uppercase text-[#92400e]'
                        }
                      >
                        {invoice.status === 'paid' ? 'Paid' : 'Pending'}
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
